### ISSUE TITLE
A lot of dependencies problem upon attempt to build ndnsim (iostreams, Click, NSC)

### ISSUE THREAD

**Issue by Mori-mori-mori** [NDN-Routing/ndnSIM#70]
I have huge troubles installing ndnsim into freshly installed Ubuntu 14 linux. Whatever route I take there are always a bunch of unsatisfied dependecies, and I haven't got a slightest clue how to resolve any of them. I started doing all according to the beginner's guide on the site, and ended up with a lot of dependencies lacking; I attempted to fix it, and all I've got in the end is dependency hell.

Edited:
It seems I've been able to build ndn-cxx with boost libraries installed under the /usr/local/ path, as recommend here: http://ndnsim.net/2.0/faq.html#installing-boost-libraries.

But the second part of the problem persists: when I'm trying to run ./waf configure --boost-includes=$BOOSTDIR/include --boost-libs=$BOOSTDIR/lib --enable-examples from ns3 directory, I'm getting this output:

root@ubuntu:/opt/ndnSIM/ns-3# ./waf configure --boost-includes=/usr/local/include --boost-libs=/usr/local/lib --enable-examples
Setting top to                           : /opt/ndnSIM/ns-3 
Setting out to                           : /opt/ndnSIM/ns-3/build 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for cc version                  : 4.8.2 
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking supported compiler CXXFLAGS     : -std=c++0x -std=c++11 
Checking supported optimizations CXXFLAGS : -O0 
Checking supported debug CXXFLAGS         : -ggdb -g3 
Checking supported warnings CXXFLAGS      : -Wall -Wno-error=deprecated-declarations -fstrict-aliasing -Wstrict-aliasing 
Checking for compilation flag -Wl,--soname=foo... support : ok 
Checking for program python                               : /usr/bin/python 
Checking for python version                               : (2, 7, 6, 'final', 0) 
Checking for library python2.7 in LIBDIR                  : yes 
Checking for program python-config                        : /usr/bin/python-config 
Checking for header Python.h                              : yes 
Checking for compilation flag -fvisibility=hidden... support : ok 
Checking for compilation flag -Wno-array-bounds... support   : ok 
Checking for pybindgen location                              : ../pybindgen (guessed) 
Checking for python module 'pybindgen'                       : 0.17.0.887 
Checking for pybindgen version                               : 0.17.0.887 
Checking for types uint64_t and unsigned long equivalence    : no 
Checking for types uint64_t and unsigned long long equivalence : yes 
Checking for the apidefs that can be used for Python bindings  : gcc-ILP32 
Checking for internal GCC cxxabi                               : complete 
Checking for python module 'pygccxml'                          : not found 
Checking boost includes                                        : 1_57 
Checking boost libs                                            : ok 
Checking for boost linkage                                     : ok 
Checking for click location                                    : not found 
Checking for program pkg-config                                : /usr/bin/pkg-config 
Checking for 'gtk+-2.0' >= 2.12                                : yes 
Checking for 'libxml-2.0' >= 2.7                               : yes 
Checking for type uint128_t                                    : not found 
Checking for type __uint128_t                                  : not found 
Checking high precision implementation                         : cairo 128-bit integer (default) 
Checking for header stdint.h                                   : yes 
Checking for header inttypes.h                                 : yes 
Checking for header sys/inttypes.h                             : not found 
Checking for header sys/types.h                                : yes 
Checking for header sys/stat.h                                 : yes 
Checking for header dirent.h                                   : yes 
Checking for header stdlib.h                                   : yes 
Checking for header signal.h                                   : yes 
Checking for header pthread.h                                  : yes 
Checking for header stdint.h                                   : yes 
Checking for header inttypes.h                                 : yes 
Checking for header sys/inttypes.h                             : not found 
Checking for library rt                                        : yes 
Checking for header netpacket/packet.h                         : yes 
Checking for header sys/ioctl.h                                : yes 
Checking for header net/if.h                                   : yes 
Checking for header net/ethernet.h                             : yes 
Checking for header linux/if_tun.h                             : yes 
Checking for header netpacket/packet.h                         : yes 
Checking for NSC location                                      : not found 
Checking for program doxygen                                   : /usr/bin/doxygen 
Checking for program tar                                       : /bin/tar 
Checking for program sphinx-build                              : /usr/bin/sphinx-build 
Checking for std::is_default_constructible                     : yes 
Checking for std::is_move_constructible                        : yes 
Checking for override specifier                                : yes 
Checking for 'libndn-cxx'                                      : not found 

I can't comprehend why 'libndn-cxx' isn't found if I just have built it on previous step.
It seems that environment variable $BOOSTDIR is empty, but even when I run it with exact paths, like ./waf configure --boost-includes=/usr/local/include --boost-libs=/usr/local/lib --enable-examples, the output is the same.

And I don't have a slightest clue what I should do about NSC, Click, uint128_t, __uint128_t, sys/inttypes.h etc not found. There is not a word about anything like this in the guide, and googling didn't help too.

**Comment by cawka** [comment]
Can you show the exact command you configured and installed ndn-cxx?

You can also consider install ndn-cxx from PPA (http://named-data.net/doc/NFD/current/INSTALL.html#install-nfd-using-the-ndn-ppa-repository-on-ubuntu-linux):

    sudo add-apt-repository ppa:named-data/ppa
    sudo apt-get update
    sudo apt-get install ndn-cxx-dev

**Comment by Mori-mori-mori** [comment]
Hi, cawka. Thank you for your answer. I don't already remember what actually I've been doing back then, I basically tried all I could, installing different components from different sources, hoping it will work eventually.

Now I've alredy done a clean reinstall of this vm, and installed boost libs with "apt-get install libboost-all-dev" and ndn-cxx with the commands you provided. After that it at least executed "./waf --configure" with "success" result (though around 10 different components were marked to not found/enabled in output) and I were able to ininitate a build proces with "./waf" command... which now just hangs my virtual machine dead after some amount of time. First it freezes it for some time (thats actually okay, ns3 itself did this to me during its building previously), but when it comes to around 1190/2450 in displayed build log, it just seems to stop completely, I can't interact with ubuntu's GUI anymore, it's just looks like a static picture. And it stops to consume a CPU time, too. A minute ago it was slowing down my system significantly, than BLAM it freezes and isn't slowing down it anymore. So it seems it really is frozen, not just very slow. I've been waiting for it to be revived for around of 30 mins already, I've repeated the process several times - still nothing.

**Comment by Mori-mori-mori** [comment]
Okay, I've did it. Dunno what helped me in the end, I rerun the whole procedure (throuhg hard reset of vm) for around 5 times before it completed. I increased vm's memory to 1,5GB, and set higher priority for the hypervisor's process itself, and after around 30 minutes it finaly compiled and I was able to run the example.

**Comment by cawka** [comment]
Yeah. c++ compiler is known to be memory hungry.  If you have assigned multiple CPUs to your vm and gave a limited amount of memory, then the recommended way to compile is to add `-j1` flag:

    ./waf -j1

PS  It's ok for multiple components to be not found during the configure stage.  You just need to make sure ndnSIM module is marked as enabled at the end of the output.

**Comment by Mori-mori-mori** [comment]
Thank you for your time and assistance.
